# Generated by Django 4.2.4 on 2023-09-13 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('status', models.SmallIntegerField(choices=[(0, '未完成'), (1, '已完成')], default=0)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
