# Generated by Django 4.2.4 on 2023-09-09 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('publish_date', models.DateField()),
                ('publisher', models.CharField(max_length=100)),
                ('authors', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'book',
            },
        ),
    ]
